name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Start backend
        run: npm start &
        env:
          CI: true

      - name: Wait for backend to be ready
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Start frontend
        run: npm run dev &
        env:
          CI: true

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:3001 --timeout 60000

      - name: Run unit tests
        run: npm test

      - name: Run Cypress tests
        run: npx cypress run
