name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            if mysqladmin ping -h"127.0.0.1" --silent; then
              break
            fi
            echo 'MySQL ainda não está pronto, esperando...'
            sleep 1
          done

      - name: Start backend
        run: npm start &
        env:
          CI: true
          DATABASE: testdb
          USERNAME: root
          PASSWORD: root
          HOST: 127.0.0.1

      - name: Wait for backend to be ready
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Start frontend
        run: npm run dev &
        env:
          CI: true

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:3001 --timeout 60000

      - name: Run unit tests
        run: npm test

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000
          config-file: cypress.config.js
