name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/*.json
          flags: unittests
          name: code-coverage-report

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19"

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Start frontend
        working-directory: ./frontend
        run: |
          npm run dev &
          npx wait-on http://localhost:3000

      - name: Run Cypress tests
        working-directory: ./frontend
        run: npx cypress run

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./frontend/coverage/*.json
          flags: e2etests
          name: e2e-code-coverage-report
