name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Start frontend
        working-directory: ./frontend
        run: |
          npm run dev &
          npx wait-on http://localhost:3000

      - name: Run Cypress tests
        working-directory: ./frontend
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev
        env:
          CYPRESS_BASE_URL: http://localhost:3000
