name: Run E2E Tests

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19"

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Start frontend
        working-directory: ./frontend
        run: |
          npm run dev &
          npx wait-on http://localhost:3000

      - name: Run Cypress tests
        working-directory: ./frontend
        run: npx cypress run
